# Generated by Django 3.2.25 on 2026-07-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20260701_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more_info',
            field=models.TextField(default=0, max_length=800),
            preserve_default=False,
        ),
    ]
