# Generated by Django 3.2.25 on 2026-07-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='more_info',
            field=models.TextField(),
        ),
    ]
