# Generated by Django 3.2.25 on 2026-07-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_post_more_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='more_info_header',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
