# Generated by Django 3.2.25 on 2026-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='counted_views',
            field=models.IntegerField(default=0),
        ),
    ]
