# Generated by Django 3.2.25 on 2026-07-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20260705_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
